updated solr_facets to fix server error
fixes #1794 We can reproduce the server error in the console with: c = RSolr.connect(url: ActiveFedora.solr_config[:url])  p = {:rows=>0, :facet=>"on", "facet.field"=>"creator_sim", "facet.limit"=>100000, "f.creator_sim.facet.limit"=>100000}  r = c.get 'select', params: p  all_facets = r['facet_counts']['facet_fields']['creator_sim'] irb(main):005:0> Hash[*all_facets] Traceback (most recent call last):         8: from bin/rails:4:in `<main>'         7: from bin/rails:4:in `require'         6: from /data0/hydra/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'         5: from /data0/hydra/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:49:in `run_command!'         4: from /data0/hydra/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:78:in `console'         3: from /data0/hydra/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands/console_helper.rb:9:in `start'         2: from /data0/hydra/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands/console.rb:65:in `start'         1: from (irb):5 SystemStackError (stack level too deep)