Investigate GenericWork 3r074v259
The export-import process has flagged one particular GenericWork as odd; could be a discrepancy between Solr and Fedora, or something else. If we reindex production and this problem goes away... fantastic. Meanwhile: GenericWork.find_each doesn't list it, and https://digital.sciencehistory.org/works/3r074v259 -- returns a 404. In the production console:  beckman = Collection.find('wh246s128') apparatus = GenericWork.find('3r074v259')  apparatus.title => ["2012-002_3680.tif"]  beckman.ordered_member_ids.include? apparatus.id => false  beckman.ordered_members.to_a.include? apparatus => false  beckman.member_ids.include? apparatus.id => true  beckman.members.to_a.include? apparatus => true