Error when a user is not in ldap is confusing
When a user has a login to ScholarSphere, but is not found in LDAP the error when you try to create a new work is Unauthorized The work you have tried to access is private  ID:  This error is quite confusing.
On my local system When I change my remote_header to 'zzz123' or any other user no longer in ldap And I click on the `new work` menu option Then I should not see an error about a work ID  ![screen shot 2017-01-27 at 7 05 30 am](   I think this could possibly happen in real life if a person had a friend or Penn State account.  It is due to the fact that users without ldap are not allowed to deposit, since they are not PSU students, faculty or staff.